@baseUrl = http://localhost:3000

### Read all films
GET {{baseUrl}}/films

### Read a film by ID
GET {{baseUrl}}/films/1

### Read a film by non-existing ID
GET {{baseUrl}}/films/9999

### minimum duration filter
GET {{baseUrl}}/films?minDuration=150

###Add a new film
POST {{baseUrl}}/films
Content-Type: application/json

{
  "title": "Inception",
  "director": "Christopher Nolan",
  "duration": 148,
  "budget": 160000000
}